micronaut:
  application:
    name: myApp
  server:
    netty:
      access-logger:
        enabled: true
        logger-name: HTTP_ACCESS_LOGGER
        log-format: "Client: %a %r %s %D ms"
  security:
    enabled: true